Camp.Web/Areas/Administration/Controllers/CampCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Camp.Data;
using Camp.Data.Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Camp.Web.Extensions;
using Microsoft.EntityFrameworkCore;

namespace Camp.Web.Areas.Administration.Controllers
{
    [Area("Administration")]
    [Authorize]
    public class CampCategoryController : BaseController
    {
        public CampCategoryController(ICampService svc, UserManager<User> userManager) : base(svc, userManager)
        {
        }

        [Route("Administrace/Kategorie-taboru")]
        public IActionResult Index()
        {
            return View(Svc.CampCategories.Items.Include(x => x.UserCreated));
        }

        [Route("Administrace/Kategorie-taboru/Vytvorit")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [Route("Administrace/Kategorie-taboru/Vytvorit")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CampCategory model)
        {
            if (ModelState.IsValid)
            {
                Svc.CreateCampCategory(model);
                Svc.Commit();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [Route("Administrace/Kategorie-taboru/Upravit/{id:int}")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = Svc.CampCategories.FindById(id);
            if (model == null)
                return NotFound();
            
            return View(model);
        }

        [Route("Administrace/Kategorie-taboru/Upravit/{id:int}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CampCategory model)
        {
            if (ModelState.IsValid)
            {
                model.UserUpdatedId = User.GetUserId();
                Svc.CampCategories.Update(model);
                Svc.Commit();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var model = Svc.CampCategories.FindById(id);
            if (model == null)
                return NotFound();

            model.UserDeletedId = User.GetUserId();
            Svc.CampCategories.Delete(model);
            Svc.Commit();

            return RedirectToAction("Index");
        }
    }
}

Camp.Web/Areas/Administration/Views/CampCategory/Create.cshtml
@model Camp.Data.Entity.CampCategory
@{
    ViewData["Title"] = "Vytvořit kategorii táborů";
    ViewData["Icon"] = "mdi-plus-circle";
}
<div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <form class="forms-sample" asp-controller="CampCategory" asp-action="Create" method="post">
                    <div class="form-group">
                        <label for="Name">Název kategorie</label>
                        <input type="text" asp-for="Name" class="form-control" placeholder="Název kategorie">
                        <span asp-validation-for="Name" class="invalid-field"></span>
                    </div>
                    <div class="form-group">
                        <div class="form-check">
                            <label for="Active" class="form-check-label">
                                <input asp-for="Active" type="checkbox" class="form-check-input" checked>
                                Aktivní
                            </label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-gradient-primary mr-2">Vytvořit</button>
                    <a asp-area="Administration" asp-controller="CampCategory" asp-action="Index" class="btn btn-light">Zpět</a>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

Camp.Web/Areas/Administration/Views/CampCategory/Edit.cshtml
@model Camp.Data.Entity.CampCategory
@{
    ViewData["Title"] = "Upravit kategorii táborů";
    ViewData["Icon"] = "mdi-lead-pencil";
}
<div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <form class="forms-sample" asp-controller="CampCategory" asp-action="Edit" method="post">
                    <input type="hidden" asp-for="Id" />
                    <input type="hidden" asp-for="Created" />
                    <input type="hidden" asp-for="UserCreatedId" />
                    <div class="form-group">
                        <label for="Name">Název kategorie</label>
                        <input type="text" asp-for="Name" class="form-control" placeholder="Název kategorie">
                        <span asp-validation-for="Name" class="invalid-field"></span>
                    </div>
                    <div class="form-group">
                        <div class="form-check">
                            <label for="Active" class="form-check-label">
                                <input asp-for="Active" type="checkbox" class="form-check-input">
                                Aktivní
                            </label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-gradient-primary mr-2">Upravit</button>
                    <a asp-area="Administration" asp-controller="CampCategory" asp-action="Index" class="btn btn-light">Zpět</a>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

Camp.Web/Areas/Administration/Views/CampCategory/Index.cshtml
@model IEnumerable<Camp.Data.Entity.CampCategory>
@{
    ViewData["Title"] = "Tábory";
    ViewData["Icon"] = "mdi-basecamp";
}

<div class="row">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Kategorie táborů</h4>
                <p class="card-description">
                    <a asp-area="Administration" asp-controller="CampCategory" asp-action="Create" class="no-underline">
                        <small>Vytvořit novou kategorii</small>
                    </a>
                </p>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>
                                    Název
                                </th>
                                <th>
                                    Stav
                                </th>
                                <th>
                                    Poslední úprava
                                </th>
                                <th>
                                    Upravil
                                </th>
                                <th>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @item.Name
                                    </td>
                                    <td>
                                        <label class="badge @(item.Active? "badge-success" : "badge-danger")">@(item.Active ? "Aktivní" : "Neaktivní")</label>
                                    </td>
                                    <td>
                                        @(item.Updated.HasValue ? item.Updated : item.Created)
                                    </td>
                                    <td>
                                       @(string.IsNullOrEmpty(item.UserUpdatedId)? item.UserCreated.Fullname : item.UserUpdated.Fullname)
                                    </td>
                                    <td>
                                        <ul class="list-inline float-right pr-2">
                                            <li class="list-inline-item">
                                                <a asp-area="Administration" asp-controller="CampCategory" asp-action="Edit" asp-route-id="@item.Id" class="text-primary" title="Upravit">
                                                    <i class="mdi mdi-lead-pencil"></i>
                                                </a>
                                            </li>
                                            <li class="list-inline-item">
                                                <i class="mdi mdi-delete text-danger pointer" title="Smazat" data-name="@item.Name" data-id="@item.Id" data-toggle="modal" data-target="#deleteModal" onclick="deleteItem(this)"></i>
                                            </li>
                                        </ul>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form asp-controller="CampCategory" asp-action="Delete" method="post">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Smazat</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <input type="hidden" name="id" id="deleteId" />
                        Opravdu chcete smazat táborovou kategorii <strong id="deleteItem"></strong>?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Zrušit</button>
                        <button type="submit" class="btn btn-danger">Smazat</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{ 
    <script>
        function deleteItem(e) {
            $("#deleteItem").html($(e).attr('data-name'));
            $("#deleteId").val($(e).attr('data-id'));
        }
    </script>
}