Camp.Web/Areas/Administration/Controllers/CampBatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Camp.Data;
using Camp.Data.Entity;
using Camp.Web.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Camp.Web.Areas.Administration.Controllers
{
    [Area("Administration")]
    [Authorize]
    public class CampBatchController : BaseController
    {
        public CampBatchController(ICampService svc, UserManager<User> userManager) : base(svc, userManager)
        {

        }

        [Route("Administrace/Turnusy-taboru")]
        public IActionResult Index()
        {
            return View(Svc.CampBatches.Items.Include(x => x.Camp).ThenInclude(x => x.CampCategory));
        }

        [Route("Administrace/Turnusy-taboru/Vytvorit")]
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Camps = new SelectList(Svc.Camps.Items.OrderBy(x => x.CampCategoryId), "Id", "Name");
            return View();
        }

        [Route("Administrace/Turnusy-taboru/Vytvorit")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CampBatch model)
        {
            if (ModelState.IsValid)
            {
                Svc.CreateCampBatch(model);
                Svc.Commit();
                return RedirectToAction("Index");
            }

            ViewBag.Camps = new SelectList(Svc.Camps.Items.OrderBy(x => x.CampCategoryId), "Id", "Name", model.CampId);
            return View(model);
        }

        [Route("Administrace/Turnusy-taboru/Upravit/{id:int}")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = Svc.CampBatches.FindById(id);
            if (model == null)
                return NotFound();

            ViewBag.Camps = new SelectList(Svc.Camps.Items.OrderBy(x => x.CampCategoryId), "Id", "Name", model.CampId);
            return View(model);
        }

        [Route("Administrace/Turnusy-taboru/Upravit/{id:int}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CampBatch model)
        {
            if (ModelState.IsValid)
            {
                model.UserUpdatedId = User.GetUserId();
                Svc.CampBatches.Update(model);
                Svc.Commit();
                return RedirectToAction("Index");
            }
            ViewBag.Camps = new SelectList(Svc.Camps.Items.OrderBy(x => x.CampCategoryId), "Id", "Name", model.CampId);
            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var model = Svc.CampBatches.FindById(id);
            if (model == null)
                return NotFound();

            model.UserDeletedId = User.GetUserId();
            Svc.CampBatches.Delete(model);
            Svc.Commit();

            return RedirectToAction("Index");
        }

        [Route("Administrace/Turnusy-taboru/Instruktori/{id:int}")]
        [HttpGet]
        public IActionResult Instructors(int id)
        {
            var model = Svc.CampBatches.Items
                .Include(x => x.InstructorCamps).ThenInclude(x => x.Instructor)
                .Include(x => x.InstructorCamps).ThenInclude(x => x.InstructorRole).FirstOrDefault(x => x.Id == id);
            
            if (model == null)
                return NotFound();

            ViewBag.Instructors = new SelectList(Svc.Instructors.Items.OrderBy(x => x.Lastname).ThenBy(x => x.Firstname), "Id", "Fullname");
            ViewBag.InstructorRoles = new SelectList(Svc.InstructorRoles.Items.OrderBy(x => x.Name), "Id", "Name");
            return View(model);
        }

        [HttpPost, ActionName("DeleteInstructor")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteInstructor(int campBatchId, int instructorId, int instructorRoleId)
        {
            Svc.RemoveInstructorCampBatch(campBatchId, instructorId, instructorRoleId);
            Svc.Commit();

            return RedirectToAction("Instructors", new { @id = campBatchId });
        }

        public JsonResult AddInstructor(int id, int instructorId, int instructorRoleId)
        {
            var res = Svc.AddInstructorToCamp(instructorId, id, instructorRoleId);
            if (res.IsOK)
                Svc.Commit();

            return Json(new { res.IsOK, res.Message });
        }
    }
}

Camp.Web/Areas/Administration/Controllers/CampController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Camp.Data;
using Camp.Data.Entity;
using Camp.Web.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Camp.Web.Areas.Administration.Controllers
{
    [Area("Administration")]
    [Authorize]
    public class CampController : BaseController
    {

        public CampController(ICampService svc, UserManager<User> userManager) : base(svc, userManager)
        {

        }

        [Route("Administrace/Tabory")]
        public IActionResult Index()
        {
            return View(Svc.Camps.Items.Include(x => x.CampCategory).Include(x => x.UserCreated).Include(x => x.UserUpdated));
        }

        [Route("Administrace/Tabory/Vytvorit")]
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(Svc.CampCategories.Items, "Id", "Name");
            return View();
        }

        [Route("Administrace/Tabory/Vytvorit")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Data.Entity.Camp model)
        {
            if (ModelState.IsValid)
            {
                Svc.CreateCamp(model);
                Svc.Commit();
                return RedirectToAction("Index");
            }

            ViewBag.Categories = new SelectList(Svc.CampCategories.Items, "Id", "Name", model.CampCategoryId);
            return View(model);
        }

        [Route("Administrace/Tabory/Upravit/{id:int}")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = Svc.Camps.FindById(id);
            if (model == null)
                return NotFound();

            ViewBag.Categories = new SelectList(Svc.CampCategories.Items, "Id", "Name", model.CampCategoryId);
            return View(model);
        }

        [Route("Administrace/Tabory/Upravit/{id:int}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Data.Entity.Camp model)
        {
            if (ModelState.IsValid)
            {
                model.UserUpdatedId = User.GetUserId();
                Svc.Camps.Update(model);
                Svc.Commit();
                return RedirectToAction("Index");
            }
            ViewBag.Categories = new SelectList(Svc.CampCategories.Items, "Id", "Name", model.CampCategoryId);
            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var model = Svc.Camps.FindById(id);
            if (model == null)
                return NotFound();

            model.UserDeletedId = User.GetUserId();
            Svc.Camps.Delete(model);
            Svc.Commit();

            return RedirectToAction("Index");
        }
    }
}

Camp.Web/Areas/Administration/Controllers/DietController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Camp.Data;
using Camp.Data.Entity;
using Camp.Web.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Camp.Web.Areas.Administration.Controllers
{
    [Area("Administration")]
    [Authorize]
    public class DietController : BaseController
    {
        public DietController(ICampService svc, UserManager<User> userManager) : base(svc, userManager)
        {

        }

        [Route("Administrace/Strava")]
        public IActionResult Index()
        {
            return View(Svc.Diets.Items.Include(x => x.UserCreated).Include(x => x.UserUpdated));
        }

        [Route("Administrace/Strava/Vytvorit")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [Route("Administrace/Strava/Vytvorit")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Diet model)
        {
            if (ModelState.IsValid)
            {
                Svc.CreateDiet(model);
                Svc.Commit();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [Route("Administrace/Strava/Upravit/{id:int}")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = Svc.Diets.FindById(id);
            if (model == null)
                return NotFound();
            
            return View(model);
        }

        [Route("Administrace/Strava/Upravit/{id:int}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Diet model)
        {
            if (ModelState.IsValid)
            {
                model.UserUpdatedId = User.GetUserId();
                Svc.Diets.Update(model);
                Svc.Commit();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var model = Svc.Diets.FindById(id);
            if (model == null)
                return NotFound();

            model.UserDeletedId = User.GetUserId();
            Svc.Diets.Delete(model);
            Svc.Commit();

            return RedirectToAction("Index");
        }
    }
}

Camp.Web/Areas/Administration/Controllers/InstructorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Camp.Data;
using Camp.Data.Entity;
using Camp.Web.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Camp.Web.Areas.Administration.Controllers
{
    [Area("Administration")]
    [Authorize]
    public class InstructorController : BaseController
    {
        public InstructorController(ICampService svc, UserManager<User> userManager) : base(svc, userManager)
        {

        }

        [Route("Administrace/Instruktori")]
        public IActionResult Index()
        {
            return View(Svc.Instructors.Items.Include(x => x.UserCreated).Include(x => x.UserUpdated));
        }

        [Route("Administrace/Instruktori/Vytvorit")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [Route("Administrace/Instruktori/Vytvorit")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Instructor model)
        {
            if (ModelState.IsValid)
            {
                Svc.CreateInstructor(model);
                Svc.Commit();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [Route("Administrace/Instruktori/Upravit/{id:int}")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = Svc.Instructors.FindById(id);
            if (model == null)
                return NotFound();

            return View(model);
        }

        [Route("Administrace/Instruktori/Upravit/{id:int}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Instructor model)
        {
            if (ModelState.IsValid)
            {
                model.UserUpdatedId = User.GetUserId();
                Svc.Instructors.Update(model);
                Svc.Commit();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var model = Svc.Instructors.FindById(id);
            if (model == null)
                return NotFound();

            model.UserDeletedId = User.GetUserId();
            Svc.Instructors.Delete(model);
            Svc.Commit();

            return RedirectToAction("Index");
        }
    }
}

Camp.Web/Areas/Administration/Views/Shared/_Footer.cshtml
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2018 <a href="http://www.raciudoli.cz/" target="_blank">Račí údolí</a>. Všechna práva vyhrazena.</span>
    </div>
</footer>

Camp.Web/Areas/Administration/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="cs">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Purple Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/Admin/vendors/iconfonts/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/Admin/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/Admin/css/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/Admin/images/favicon.png" />
</head>
<body>
    <div class="container-scroller">
        <!-- partial:_Navbar.html -->
        <partial name="_Navbar" />
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:_Sidebar.html -->
            <partial name="_Sidebar" />
            <!-- partial -->
            <div class="main-panel">
                <div class="content-wrapper">
                    <div class="page-header">
                        <h3 class="page-title">
                            <span class="page-title-icon bg-gradient-primary text-white mr-2">
                                <i class="mdi @ViewData["Icon"]"></i>
                            </span>
                            @ViewData["Title"]
                        </h3>
                    </div>
                    @RenderBody()
                </div>
                <!-- content-wrapper ends -->
                <!-- partial:_Footer.html -->
                <partial name="_Footer" />
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/Admin/vendors/js/vendor.bundle.base.js"></script>
    <script src="~/Admin/vendors/js/vendor.bundle.addons.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page-->
    <!-- End plugin js for this page-->
    <!-- inject:js -->
    <script src="~/Admin/js/off-canvas.js"></script>
    <script src="~/Admin/js/misc.js"></script>
    <!-- endinject -->
    @RenderSection("Scripts", required: false)
</body>
</html>

Camp.Web/Areas/Administration/Views/Shared/_Navbar.cshtml
@using Microsoft.AspNetCore.Identity
@using Camp.Web.Extensions
@inject UserManager<Camp.Data.Entity.User> UserManager

<nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <a class="navbar-brand brand-logo" href="index.html"><img src="~/Admin/images/logo.svg" alt="logo" /></a>
        <a class="navbar-brand brand-logo-mini" href="index.html"><img src="~/Admin/images/logo-mini.svg" alt="logo" /></a>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-stretch">
        <div class="search-field d-none d-md-block">
            <form class="d-flex align-items-center h-100" action="#">
                <div class="input-group">
                    <div class="input-group-prepend bg-transparent">
                        <i class="input-group-text border-0 mdi mdi-magnify"></i>
                    </div>
                    <input type="text" class="form-control bg-transparent border-0" placeholder="Search projects">
                </div>
            </form>
        </div>
        <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item nav-profile dropdown">
                <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                    <div class="nav-profile-img">
                        <img src="~/Admin/images/faces/face10.jpg" alt="image">
                        <span class="availability-status online"></span>
                    </div>
                    <div class="nav-profile-text">
                        <p class="mb-1 text-black">@UserManager.GetUserFirstname(User)</p>
                    </div>
                </a>
                <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
                    <a class="dropdown-item" href="#">
                        <i class="mdi mdi-cached mr-2 text-success"></i>
                        Activity Log
                    </a>
                    <div class="dropdown-divider"></div>

                    <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "Administration" })" method="post">
                        <button type="submit" class="dropdown-item pointer">
                            <i class="mdi mdi-logout mr-2 text-primary"></i>
                            Odhlásit
                        </button>
                    </form>

                </div>
            </li>
            <li class="nav-item d-none d-lg-block full-screen-link">
                <a class="nav-link pointer">
                    <i class="mdi mdi-fullscreen" id="fullscreen-button"></i>
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link count-indicator dropdown-toggle" id="messageDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                    <i class="mdi mdi-email-outline"></i>
                    <span class="count-symbol bg-warning"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="messageDropdown">
                    <h6 class="p-3 mb-0">Messages</h6>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <img src="~/Admin/images/faces/face4.jpg" alt="image" class="profile-pic">
                        </div>
                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                            <h6 class="preview-subject ellipsis mb-1 font-weight-normal">Mark send you a message</h6>
                            <p class="text-gray mb-0">
                                1 Minutes ago
                            </p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <img src="~/Admin/images/faces/face2.jpg" alt="image" class="profile-pic">
                        </div>
                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                            <h6 class="preview-subject ellipsis mb-1 font-weight-normal">Cregh send you a message</h6>
                            <p class="text-gray mb-0">
                                15 Minutes ago
                            </p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <img src="~/Admin/images/faces/face3.jpg" alt="image" class="profile-pic">
                        </div>
                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                            <h6 class="preview-subject ellipsis mb-1 font-weight-normal">Profile picture updated</h6>
                            <p class="text-gray mb-0">
                                18 Minutes ago
                            </p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <h6 class="p-3 mb-0 text-center">4 new messages</h6>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
                    <i class="mdi mdi-bell-outline"></i>
                    <span class="count-symbol bg-danger"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
                    <h6 class="p-3 mb-0">Notifications</h6>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-success">
                                <i class="mdi mdi-calendar"></i>
                            </div>
                        </div>
                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                            <h6 class="preview-subject font-weight-normal mb-1">Event today</h6>
                            <p class="text-gray ellipsis mb-0">
                                Just a reminder that you have an event today
                            </p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-warning">
                                <i class="mdi mdi-settings"></i>
                            </div>
                        </div>
                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                            <h6 class="preview-subject font-weight-normal mb-1">Settings</h6>
                            <p class="text-gray ellipsis mb-0">
                                Update dashboard
                            </p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-info">
                                <i class="mdi mdi-link-variant"></i>
                            </div>
                        </div>
                        <div class="preview-item-content d-flex align-items-start flex-column justify-content-center">
                            <h6 class="preview-subject font-weight-normal mb-1">Launch Admin</h6>
                            <p class="text-gray ellipsis mb-0">
                                New admin wow!
                            </p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <h6 class="p-3 mb-0 text-center">See all notifications</h6>
                </div>
            </li>
            <li class="nav-item nav-settings d-none d-lg-block">
                <a class="nav-link" href="#">
                    <i class="mdi mdi-format-line-spacing"></i>
                </a>
            </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
        </button>
    </div>
</nav>

Camp.Web/Areas/Administration/Views/Shared/_Sidebar.cshtml
@using Microsoft.AspNetCore.Identity
@using Camp.Web.Extensions
@inject UserManager<Camp.Data.Entity.User> UserManager


<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item nav-profile">
            <a href="#" class="nav-link">
                <div class="nav-profile-image">
                    <img src="~/Admin/images/faces/face10.jpg" alt="profile">
                    <span class="login-status online"></span> <!--change to offline or busy as needed-->
                </div>
                <div class="nav-profile-text d-flex flex-column">
                    <span class="font-weight-bold mb-2">@UserManager.GetUserFirstname(User)</span>
                    <span class="text-secondary text-small">Admin</span>
                </div>
                <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
            </a>
        </li>
        <li class="nav-item">
            <a asp-area="Administration" asp-controller="Home" asp-action="Index" class="nav-link">
                <span class="menu-title">Přehled</span>
                <i class="mdi mdi-home menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#ui-camps" aria-expanded="false" aria-controls="ui-camps">
                <span class="menu-title">Tábory</span>
                <i class="menu-arrow"></i>
                <i class="mdi mdi-basecamp menu-icon"></i>
            </a>
            <div class="collapse" id="ui-camps">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                        <a asp-area="Administration" asp-controller="CampBatch" asp-action="Index" class="nav-link">Seznam turnusů</a>
                    </li>
                    <li class="nav-item">
                        <a asp-area="Administration" asp-controller="Camp" asp-action="Index" class="nav-link">Seznam táborů</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="Administration" asp-controller="Instructor" asp-action="Index">Instruktoři</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="Administration" asp-controller="InstructorRole" asp-action="Index">Role instruktorů</a>
                    </li>
                    <li class="nav-item">
                        <a asp-area="Administration" asp-controller="CampCategory" asp-action="Index" class="nav-link">Kategorie táborů</a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="nav-item">
            <a asp-area="Administration" asp-controller="Diet" asp-action="Index" class="nav-link">
                <span class="menu-title">Strava</span>
                <i class="mdi mdi-bowl menu-icon"></i>
            </a>
        </li>
    </ul>
</nav>